name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  # Add Release trigger on tag push
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      run: rustup update stable 
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
  release:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      run: rustup update stable
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/rust_exampl1.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}